### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by xsa-dev** [notadamking/RLTrader#149]
Hi! I am try use RLTrader, but this error blocked me: **_ModuleNotFoundError: No module named 'tensorflow.contrib'._**
ENV: Google Collab with GPU.

This steps make an error:
1) !git init && git remote add origin https://github.com/notadamking/RLTrader.git && git pull origin master
2) !pip install -r requirements.txt
3) !python ./cli.py update-static-data

**Comment by MichaelQuaMan** [comment]
@xsa-dev Your version of `Tensorflow` is newer than RLTrader is expecting. `Tensorflow` stopped using "contrib". 

I had to lower my version and `tensorflow==1.15.0` is working without issue.
