### ISSUE TITLE
Optimal Hyper-parameters

### ISSUE THREAD

**Issue by tislamov** [notadamking/RLTrader#16]
Great work!  Can you please post your best hyper-parameters found by optimize.py? I want to compare your results with mine.

**Comment by notadamking** [comment]
Sortino params (Best trial: 455398.5):

```python
{'cliprange': 0.3838833398771404, 'confidence_interval': 0.8100538836579667, 'ent_coef': 2.2986983190512612e-06, 'forecast_len': 4.730444664178924, 'gamma': 0.9471575125156161, 'lam': 0.8983738705323411, 'learning_rate': 0.0015741188587479822, 'n_steps': 243.43124303268107, 'noptepochs': 35.778727741355404}
```

Profit params (Best trial: 38864.61):

```py
{'cliprange': 0.18171577216380486, 'confidence_interval': 0.8299903990879873, 'ent_coef': 0.058311932079135285, 'forecast_len': 2.7551333410672285, 'gamma': 0.9540947637066638, 'lam': 0.83488862588063, 'learning_rate': 5.34448096328516e-05, 'n_steps': 39.58562503420813, 'noptepochs': 23.5774187300346}
```

Omega params (Best trial: 7338.22):

```py
{'cliprange': 0.24459328978411837, 'confidence_interval': 0.8755049470318887, 'ent_coef': 0.027326192405747952, 'forecast_len': 2.1992583581527034, 'gamma': 0.950470738014891, 'lam': 0.9475367647108637, 'learning_rate': 0.0004360742524710917, 'n_steps': 178.73715989610724, 'noptepochs': 6.550643994196925}
```

Calmar params (Best trial: inf)

```py
{'cliprange': 0.12815377506727943, 'confidence_interval': 0.938802632983171, 'ent_coef': 0.003002638685121034, 'forecast_len': 2.537952330636492, 'gamma': 0.9776260043273306, 'lam': 0.870730772858517, 'learning_rate': 0.0038901835069753603, 'n_steps': 865.8583275568369, 'noptepochs': 17.41301148514281}
```

The Calmar optimization gave me lots of problems and never achieved a better result than `inf`, so I ended up testing the final Calmar agent with the Sortino hyper-parameters. I haven't experimented much else with swapping hyper-parameter sets between reward functions, but it would be interesting to see the results.

**Comment by notadamking** [comment]
All of the agents seem to benefit from a short `forecast_len`, `gamma` (decay) of around .95, and a `learning_rate` of  around 1E-3 or below.

**Comment by PromediaB** [comment]
How many time its take you for optimize.py with your configuration ?  i have swtiched to only 10 trials with 60 days on csv file and waiting more than 1 hour.  How many time.

Im running on no-gpu sever with 8 processor and 16G memory.

**Comment by xeroquark** [comment]
@PromediaB `optimize.py` ran more than 18 hours on GTX 1080, quadcore machine. I had to kill the process in the end.. I'll start with @notadamking's suggested hyperparams to bypass this part for now. Improving the code in the hyperparam search would be extremely useful in the future.

**Comment by PromediaB** [comment]
Thank you @xeroquark and sorry for this newbie question, but how can i implement the hyperparams on the train ? can you please share the train.py including this param or any other file that should be changed.

thank you

**Comment by PromediaB** [comment]
@notadamking any answer to my last question where to put the hyperparam ? i tried to place it on train.py as :

train_env = DummyVecEnv([lambda: BitcoinTradingEnv(
    train_df, reward_func=reward_strategy, forecast_len=int(['4.730444664178924']),confidence_interval=['0.8100538836579667'])])

test_env = DummyVecEnv([lambda: BitcoinTradingEnv(
    test_df, reward_func=reward_strategy, forecast_len=int(['4.730444664178924']), confidence_interval=['0.8100538836579667'])])

model_params = {
    'n_steps': int(['243.43124303268107']),
    'gamma': ['0.9471575125156161'],
    'learning_rate': ['0.0015741188587479822'],
    'ent_coef': ['2.2986983190512612e-06'],
    'cliprange': ['0.3838833398771404'],
    'noptepochs': int(['noptepochs']),
    'lam': ['0.8983738705323411'],
}



but not working

**Comment by tislamov** [comment]
@PromediaB 
> @notadamking any answer to my last question where to put the hyperparam ? i tried to place it on train.py as :
> 
> train_env = DummyVecEnv([lambda: BitcoinTradingEnv(
> train_df, reward_func=reward_strategy, forecast_len=int(['4.730444664178924']),confidence_interval=['0.8100538836579667'])])
> 
> test_env = DummyVecEnv([lambda: BitcoinTradingEnv(
> test_df, reward_func=reward_strategy, forecast_len=int(['4.730444664178924']), confidence_interval=['0.8100538836579667'])])
> 
> model_params = {
> 'n_steps': int(['243.43124303268107']),
> 'gamma': ['0.9471575125156161'],
> 'learning_rate': ['0.0015741188587479822'],
> 'ent_coef': ['2.2986983190512612e-06'],
> 'cliprange': ['0.3838833398771404'],
> 'noptepochs': int(['noptepochs']),
> 'lam': ['0.8983738705323411'],
> }
> 
> but not working

You need to do this:

study_name = 'ppo2' + reward_strategy
#study = optuna.load_study(study_name=study_name, storage=params_db_file)
#params = study.best_trial.params

params = {'cliprange': 0.3838833398771404, 'confidence_interval': 0.8100538836579667, 'ent_coef': 2.2986983190512612e-06, 'forecast_len': 4.730444664178924, 'gamma': 0.9471575125156161, 'lam': 0.8983738705323411, 'learning_rate': 0.0015741188587479822, 'n_steps': 243.43124303268107, 'noptepochs': 35.778727741355404}

print("Training PPO2 agent with params:", params)
#print("Best trial reward:", -1 * study.best_trial.value)

**Comment by notadamking** [comment]
Thanks @tislamov, your code looks like it should be correct, though I haven't tested it.

@PromediaB, you can fix your original code by changing it to the following:

```python
train_env = DummyVecEnv([lambda: BitcoinTradingEnv(
train_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])

test_env = DummyVecEnv([lambda: BitcoinTradingEnv(
test_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])

model_params = {
'n_steps': 243,
'gamma': 0.94715,
'learning_rate': 0.00157,
'ent_coef': 2.29869,
'cliprange':  0.38388,
'noptepochs': 35,
'lam': 0.89837,
}
```

**Comment by JakubSledz** [comment]
Hi all. I used this params and I ended with -40% profit :) Any ideas why my results are so much different?

**Comment by Kalelv45** [comment]
> ```python
> train_env = DummyVecEnv([lambda: BitcoinTradingEnv(
> train_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])
> 
> test_env = DummyVecEnv([lambda: BitcoinTradingEnv(
> test_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])
> 
> model_params = {
> 'n_steps': 243,
> 'gamma': 0.94715,
> 'learning_rate': 0.00157,
> 'ent_coef': 2.29869,
> 'cliprange':  0.38388,
> 'noptepochs': 35,
> 'lam': 0.89837,
> }
> ```

Once the training is done, how should I run the test.py file? 
I get this error: 

File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/study.py", line 129, in best_trial
    return self.storage.get_best_trial(self.study_id)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/optuna/storages/base.py", line 182, in get_best_trial
    raise ValueError('No trials are completed yet.')
ValueError: No trials are completed yet.


yet the trained has finished with no problems...
