### ISSUE TITLE
Pre-trained Sortino and Profit models

### ISSUE THREAD

**Issue by samfultonschool** [notadamking/RLTrader#17]
Would it be possible to get the model that was referenced in the article making 850% profit? 
Thanks

**Comment by PromediaB** [comment]
you can fix your original code by changing it to the following on train.py without running optimize :

```
train_env = DummyVecEnv([lambda: BitcoinTradingEnv(
train_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])

test_env = DummyVecEnv([lambda: BitcoinTradingEnv(
test_df, reward_func=reward_strategy, forecast_len=4, confidence_interval=0.81)])

model_params = {
'n_steps': 243,
'gamma': 0.94715,
'learning_rate': 0.00157,
'ent_coef': 2.29869,
'cliprange':  0.38388,
'noptepochs': 35,
'lam': 0.89837,
}
```

**Comment by notadamking** [comment]
While it's much more fun to train the agents yourself, I do understand that not everyone has the hardware. Here are the two best Sortino models and the two best Profit models mentioned in the article (I think so at least, please make sure I uploaded the correct ones).

Sortino 1: https://www.dropbox.com/s/lqjf7pqxd7il38h/ppo2_sortino_2.pkl?dl=0
Sortino 2: https://www.dropbox.com/s/dkvre43zikagfik/ppo2_sortino_3.pkl?dl=0

Profit 1: https://www.dropbox.com/s/a9diw09vuce5v4c/ppo2_profit_4.pkl?dl=0
Profit 2: https://www.dropbox.com/s/zjc9rvgdgx3gul6/ppo2_profit_2.pkl?dl=0

**Comment by andy121090** [comment]
@notadamking Do you have by chance the `params.db`? I am trying to run the `test.py`. Or did you wrote down the hyperparameters for Sortino 1/2 and Profit 1/2?

**Comment by archenroot** [comment]
My optimize.py runs for 1 day and having finished 100 out of 1000 trials :-)

**Comment by notadamking** [comment]
@andy121090 The hyper-parameters used to train all of the agents in the article have been posted in #16

**Comment by archenroot** [comment]
When loading into test.py the profit pkl files, I get:
```
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (1,55) (1,61) 

```

**Comment by archenroot** [comment]
I think its also bit weird we train and test on same data, we should put more datasets in place.... or I overlook something (I ususaly train on 70 and test on 30 precents models like xgboosts or arima, regression, forest, evolution)?

**Comment by archenroot** [comment]
Could be reason for so good profitability be a fact that in test.py you are using same data as for training to test agent against?
```
test_len = int(len(df) * 0.2)
train_len = int(len(df)) - test_len

test_df = df[train_len:]  note the train_len here.....
```

**Comment by archenroot** [comment]
Q: Have you considered also transaction fees and minimum transaction amount, also orderbook shifting, etc. It can affect the profitability of course, also not sucessful trade (someone is faster to buy/sell)

**Comment by silentrob** [comment]
@archenroot I tested the model on Binance BTC/USDT (completely unseen)  and still saw a 900% return. There was long periods of drawdowns and the model sat below the SMA Crossover for quite a while but it is still profitable. Obviously you would still want to factor in fees.

**Comment by archenroot** [comment]
that's crazy, ho do you feed the data stream into model, do you use queue to append new timeseries, or some loop with wait for new data? I am thinking about what aproach would be best?

**Comment by archenroot** [comment]
@silentrob - or can you share the code which can connect to coinbase sandbox?

**Comment by silentrob** [comment]
So I'm not streaming data in yet, as mentioned in other comments, that is coming in the next post. I just downloaded and changed the coinbase_hourly to binance_hourly using the pre-trained model provided (also from another issue/comment)

**Comment by archenroot** [comment]
So this is api to all: https://github.com/ccxt/ccxt

**Comment by archenroot** [comment]
Regarding streaming, nice example is here:
https://mapr.com/blog/streaming-predictive-maintenance-for-iot-using-tensorflow-part-1/

1. part makes model work on history data 
2. second is making it working in streaming environment

**Comment by andy121090** [comment]
@notadamking Could you please also share the hardware specs which you used to train the agents? How long did it take? I intend to run the code in the google cloud, but I have no idea about the GPU which I should use to avoid out-of-memory errors.

**Comment by rhamnett** [comment]
@notadamking  Looks like there is some sort of memory leak, I optimised on an EC2 instance p3.2xlarge overnight and ended up filling the 60G of RAM.

**Comment by Kalelv45** [comment]
> @notadamking Looks like there is some sort of memory leak, I optimised on an EC2 instance p3.2xlarge overnight and ended up filling the 60G of RAM.

Same here

**Comment by archenroot** [comment]
I run optimize on 1000 samples and memory consumption went over 100GB... I have 128GB ram and about 32 gb swap, but the system got exhausted I killed the session, not sure where si the root cause.
