### ISSUE TITLE
ValueError: The provided tag was already used for this event type

### ISSUE THREAD

**Issue by ktattan** [notadamking/RLTrader#24]
I am running this code in google colab to take advantage of the GPU's, but every time I run it, I get the error in the title.

At the beginning of the notebook, I install all the dependancies

```
!git clone https://github.com/notadamking/Bitcoin-Trader-RL.git
!pip install ta
!pip install empyrical
!pip install optuna
!pip install gym
!pip install stable-baselines
!pip install scikit-learn
!pip install tensorflow-gpu

....

!python3 optimize.py


[I 2019-06-09 08:56:20,043] A new study created with name: ppo2_sortino
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/stable_baselines/common/input.py:26: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/stable_baselines/common/policies.py:195: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
[W 2019-06-09 08:58:47,691] Setting status of trial#0 as TrialState.FAIL because of the following error: ValueError('The provided tag was already used for this event type',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 399, in _run_trial
    result = func(trial)
  File "optimize.py", line 88, in optimize_agent
    model.learn(evaluation_interval)
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/ppo2/ppo2.py", line 307, in learn
    writer=writer, states=mb_states))
  File "/usr/local/lib/python3.6/dist-packages/stable_baselines/ppo2/ppo2.py", line 245, in _train_step
    writer.add_run_metadata(run_metadata, 'step%d' % (update * update_fac))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/summary/writer/writer.py", line 264, in add_run_metadata
    raise ValueError("The provided tag was already used for this event type")
ValueError: The provided tag was already used for this event type
```

The notebook crashes shortly after a 3-5 of the same errors are raised for every bayesian optimisation trial. I am unsure if this is an optuna error or a tensorflow error. I couldn't find much info online regarding the error. Any idea what may be causing this and how to fix it?

**Comment by silentrob** [comment]
I had issues with Python 3.7 (and tensorflow) and didn't bother trying 3.6. I might try Python 3.5.7 and see if you get the same error.

**Comment by ktattan** [comment]
Thanks @silentrob, I wonder if this has something to do with tensorflow 1 versus tensorflow 2? I'll try with a different python version in the meantime

**Comment by ktattan** [comment]
@notadamking maybe you could upload a yaml file with your conda environment to the git repo so we can get the exact same package versions as you? It may also be useful to post your python version.

**Comment by yinfeng2016** [comment]
> @notadamking maybe you could upload a yaml file with your conda environment to the git repo so we can get the exact same package versions as you? It may also be useful to post your python version.

@ktattan I got same error when using google colab. have you found a solution for this?

**Comment by rshtirmer** [comment]
Here’s a fix.. change 
`model_params = optimize_ppo2(trial)
    model = PPO2(MlpLnLstmPolicy, train_env, verbose=0, nminibatches=1,
                 tensorboard_log=Path("./tensorboard").name, **model_params) `
To this:
`model_params = optimize_ppo2(trial)
    model = PPO2(MlpLnLstmPolicy, train_env, verbose=0, nminibatches=1, **model_params) `

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by abhimalamkar** [comment]
Where do you make this change?
