### ISSUE TITLE
Create DataLoader class to incorporate multiple data sets

### ISSUE THREAD

**Issue by marvin-hansen** [notadamking/RLTrader#3]
The Alpha Vantage web service provides real-time and historical equity, index, and crypto data. 

The service is free, requiring only a free, email registration. The service provides daily, weekly, and monthly history for both domestic and international markets, with up to 20 years of history. 

For daily data, adjusted close prices are available to account for dividends and splits so no more manual adjustment anymore:-)

The service can also provide real-time price bars at a resolution of 1 minute or higher, for up to 10 recent days.

https://www.alphavantage.co/

There is a convienent Python wrapper. 
https://github.com/RomelTorres/alpha_vantage

I can offer help, if contributions are welcome

**Comment by notadamking** [comment]
Contributions are always welcome. This is a great idea! I will work on getting the DataLoader merged into the library.

**Comment by PromediaB** [comment]
Hello @notadamking,

Did you tried with Minutes history if you are getting more trade or more profit?

**Comment by notadamking** [comment]
I have tried with 1-minute OHCLV data from the Kaggle dataset. This is actually the data set the agents were trained on for the first article. However, this data set took far too long to optimize/train on and it achieved worse results.

**Comment by notadamking** [comment]
I have updated the title as I believe the DataLoader should veer away from AlphaVantage and instead aim to support any data set.

**Comment by uBadRequest** [comment]
> I have updated the title as I believe the DataLoader should veer away from AlphaVantage and instead aim to support any data set.

Do you have a discord channel that we could join?

**Comment by notadamking** [comment]
I have just now created a discord server for anyone interested: https://discord.gg/ZZ7BGWh

**Comment by notadamking** [comment]
On a side note, I will be taking on this DataLoader today.

**Comment by marvin-hansen** [comment]
Don't know whether the issue is still active, but since scope has expanded, just open another issue.
