### ISSUE TITLE
Absolute diff or percentege diff for reward calculation

### ISSUE THREAD

**Issue by ieow** [notadamking/RLTrader#41]
In the reward calculation, the returns used for ratio calculation is absolute diff.
Isn't the 'returns' used should be percentage diff ?

```
    def _reward(self):
        length = min(self.current_step, self.forecast_len)
        returns = np.diff(self.net_worths[-length:])
```

**Comment by notadamking** [comment]
Ahh, if this is the case, I will gladly accept a PR to fix it. Although, the results should be fairly similar as the reward should scale similarly either way.

**Comment by ieow** [comment]
I think the fix should be

```
    def _reward(self):
        length = min(self.current_step, self.forecast_len)
        returns = np.diff(self.net_worths[-length:]) / self.net_worths[1-length:]
```
Not sure if it need a PR
