### ISSUE TITLE
QuantConnect Backtest, Paper & Live Trading Results

### ISSUE THREAD

**Issue by marvin-hansen** [notadamking/RLTrader#51]
Hey Adam, 

great work and well written article. Thank you for sharing.

Would you consider implementing your system on QauntConnect?

https://www.quantconnect.com/

You may or may not open source code, but sharing the backtest and 
paper trading results adds a ton of credibility to your work. All it takes is to implement a scheduled event handler.

https://www.quantconnect.com/docs/key-concepts/developing-in-the-ide

My last algo still runs in paper trading, but the insights gained from how it performs under real market conditions were critical to developing the next generation.

Cheers and keep up the amazing work.

**Comment by andrewczgithub** [comment]
I wanted to ask this!
This would be really awesome if a prototype could be thrown together.
There back testing platform is very realistic.
Best,
Andrew

**Comment by notadamking** [comment]
@marvin-hansen, @andrewczgithub, thanks for your interest in this repo! I would love to see this algorithm implemented in QuantConnect, though I am very short on time these days. Perhaps someone who is more familiar with the platform can implement it and share their results here?

**Comment by marvin-hansen** [comment]
@notadamking Implementation should be tracked in another issue by whoever is doing it.
