### ISSUE TITLE
Use of training data and multiple episodes

### ISSUE THREAD

**Issue by lucacarniato** [notadamking/RLTrader#52]
I have the following two questions about optimize.py :

The model appears to be trained always in the first portion of train_df, from 0 to len(len(train_df) / n_evaluations. Are the other portions of train_df used in the loop over n_evaluations?

Why is an evaluation of n_test_episodes required for calculating a mean reward? 

Thank you.

**Comment by notadamking** [comment]
It is not required, though it improves the accuracy of the test as the PPO2 algorithm is non-deterministic.
