### ISSUE TITLE
How to modify environment to include lookback_window_size with MlpPolicy

### ISSUE THREAD

**Issue by maxmatical** [notadamking/RLTrader#66]
Since the agent switched from MlpPolicy to the MlpLstmPolicy, the environment no longer has the lookback_window_size, which tells the agent how many timesteps in the past to include in observation.

I want to test the performance of the MlpPolicy against MlpLstmPolicy with all other hyperparameters the same. I can use the MlpPolicy with the current environment, but I would like to include the past observations into the current step. What would be the best way to do this?

**Comment by notadamking** [comment]
You will need to update `_next_observation` to include multiple time steps.
