### ISSUE TITLE
Any pointers of how this would adapt to live data?

### ISSUE THREAD

**Issue by sph3rex** [notadamking/RLTrader#67]
Even though is a great intro to RL stuff and pretty well documented by the articles, I can't get my head around how live data would fit the picture here, so I'm guessing that _next_observation needs some tweaking/changing, but I'm not really sure of how to tackle the whole thing, because probably I'm missing some basics here :). Any pointers would be appreciated (maybe some examples from openai's gym repo that I've missed). Thank you.

**Comment by nachovoss** [comment]
I think one approach would be,  when running create 2 dataframes  one with the preloded coinbase_hourly, and a new one with the new data , then try dataFrame.append(other, ignore_index=False, verify_integrity=False, sort=TRUE), and work on a loop  constantly updating the resulting df  ,  making prediction, remember to erase the last  row in the df  and unused variables every iteration of the loop to avoid running out of ram. 
Haven't tested yet it's just an idea, hope it helps

**Comment by notadamking** [comment]
Closing this in favor of keeping the discussion in #21.
