### ISSUE TITLE
How to return account_history?

### ISSUE THREAD

**Issue by maxmatical** [notadamking/RLTrader#90]
If I want the environment to return the numpy array of account_histories so I can pull out values or do visualizations, how can I do that?

**Comment by notadamking** [comment]
This is currently not supported, though you are welcome to submit a PR that makes this possible.

**Comment by maxmatical** [comment]
Do you have an idea/documentation on how to return custom variables? I've tried writing a function that returns the account_history, but I get `AttributeError: 'DummyVecEnv' object has no attribute 'return_acc_hist'` and I can't find any documentation on how to return custom variables in an environment

**Comment by bzier** [comment]
`DummyVecEnv` is a wrapper around other environments (see [here](https://stable-baselines.readthedocs.io/en/master/guide/vec_envs.html)). It includes a method called `env_method`, which should allow you to invoke any method defined on the underlying environment, like your `return_acc_hist` method.

**Comment by maxmatical** [comment]
Do I call it like `env.env_method(return_acc_hist)` or something like that? I tried that but I get `NameError: name '_return_trade_history' is not defined` so I feel like I'm doing something wrong

**Comment by maxmatical** [comment]
The issue is solved, I had to write the method name as a string `env.env_method('return_acc_hist')`
