### ISSUE TITLE
Question: why action changed to all in/out instead of partial(percentage of fund)

### ISSUE THREAD

**Issue by ieow** [notadamking/RLTrader#94]
Why action changed to all in/out instead of partial(percentage of fund) which used by previous version.

**Comment by notadamking** [comment]
The model has been extremely simplified to remove any sources of bias/overfitting/noise. One of these changes was to decrease the number of discrete actions, though it is unclear how this has affected the performance. It would be great for someone to test the performance of the agent with more discrete actions to see how it affects performance.
