### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Prossi79** [notadamking/RLTrader#96]
Hello, I tried to install the RLTrader without GPU :

`(base) root@vmanager6003:~/RLTrader# pip install -r requirements.no-gpu.txt
Requirement already satisfied: numpy in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 1)) (1.16.4)
Requirement already satisfied: pandas in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 2)) (0.24.2)
Requirement already satisfied: sklearn in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 3)) (0.0)
Requirement already satisfied: matplotlib in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 4)) (3.1.0)
Requirement already satisfied: gym in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 5)) (0.13.0)
Requirement already satisfied: stable_baselines in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 6)) (2.6.0)
Requirement already satisfied: optuna in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 7)) (0.12.0)
Requirement already satisfied: ta in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 8)) (0.4.5)
Requirement already satisfied: statsmodels==0.10.0rc2 in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 9)) (0.10.0rc2)
Requirement already satisfied: empyrical in /root/miniconda3/lib/python3.7/site-packages (from -r requirements.base.txt (line 10)) (0.5.0)
Collecting ccxt (from -r requirements.base.txt (line 11))
  Downloading https://files.pythonhosted.org/packages/ad/9d/9b73813e84bcfcc8f34bedf2a848a15bb5dd1777a836033adebca44ddd69/ccxt-1.18.902-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 6.1MB/s 
Collecting psycopg2 (from -r requirements.base.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/5c/1c/6997288da181277a0c29bc39a5f9143ff20b8c99f2a7d059cfb55163e165/psycopg2-2.8.3.tar.gz (377kB)
    100% |████████████████████████████████| 378kB 9.9MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/psycopg2.egg-info
    writing pip-egg-info/psycopg2.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/psycopg2.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/psycopg2.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/psycopg2.egg-info/SOURCES.txt'
    
    Error: pg_config executable not found.
    
    pg_config is required to build psycopg2 from source.  Please add the directory
    containing pg_config to the $PATH or specify the full executable path with the
    option:
    
        python setup.py build_ext --pg-config /path/to/pg_config build ...
    
    or with the pg_config option in 'setup.cfg'.
    
    If you prefer to avoid building psycopg2 from source, please install the PyPI
    'psycopg2-binary' package instead.
    
    For further information please check the 'doc/src/install.rst' file (also at
    <http://initd.org/psycopg/docs/install.html>).
    
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ghil6esx/psycopg2/
`

**Comment by athon-millane** [comment]
Just encountered this on mac, resolved by `brew install postgresql`.

**Comment by g0lemXIV** [comment]
You can simply install python-dev if You are creating new environment from requirements.txt
`sudo apt-get install libpq-dev python-dev`
